name: turing-experiments
channels:
  - conda-forge
dependencies:
  - aiohttp=3.8.3=py311he2be06e_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=23.1.0=py311h267d04e_0
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - brotlipy=0.7.0=py311he2be06e_1005
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2022.12.7=h4653dfc_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py311hae827db_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.7=py311hd6ee22a_0
  - cryptography=39.0.0=py311h507f6e9_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - darglint=1.8.1=pyhd8ed1ab_0
  - debugpy=1.6.6=py311ha397e9f_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fire=0.4.0=pyh44b312d_0
  - flake8=6.0.0=pyhd8ed1ab_0
  - flake8-black=0.3.5=pyhd8ed1ab_0
  - flake8-docstrings=1.7.0=pyhd8ed1ab_0
  - fonttools=4.38.0=py311he2be06e_1
  - freetype=2.12.1=hd633e50_1
  - frozenlist=1.3.3=py311he2be06e_0
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.30=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - ipykernel=6.21.1=pyh736e0ef_0
  - ipython=8.9.0=pyhd1c38e8_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=he4db4b2_2
  - jupyter_client=8.0.2=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py311h267d04e_0
  - kiwisolver=1.4.4=py311hd6ee22a_1
  - lcms2=2.14=h481adae_1
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.17=h1a8c8d9_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_27
  - libgfortran5=11.3.0=hdaf2cc0_27
  - liblapack=3.9.0=16_osxarm64_openblas
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=3.21.12=hb5ab8b9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libtiff=4.5.0=h5dffbdd_2
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.7=h7cfbb63_0
  - matplotlib-base=3.6.3=py311h99a5f44_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - multidict=6.0.4=py311he2be06e_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numpy=1.24.2=py311h60f8152_0
  - openai=0.26.4=pyhd8ed1ab_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openpyxl=3.1.0=py311he2be06e_0
  - openssl=3.0.8=h03a7124_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py311h4eec4a9_0
  - pandas-stubs=1.5.3.230203=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.11.0=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py311h627eb56_1
  - pip=23.0=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - plotly=5.13.0=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - protobuf=4.21.12=py311ha397e9f_0
  - psutil=5.9.4=py311he2be06e_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyflakes=3.0.1=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.0=h3ba56d0_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyyaml=6.0=py311he2be06e_5
  - pyzmq=25.0.0=py311h0f351f6_0
  - readline=8.1.2=h46ed386_0
  - requests=2.28.2=pyhd8ed1ab_0
  - scikit-learn=1.2.1=py311hba7d9bc_0
  - scipy=1.10.0=py311h0bcca16_2
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - sentry-sdk=1.14.0=pyhd8ed1ab_0
  - setproctitle=1.3.2=py311he2be06e_1
  - setuptools=67.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py311h4add359_2
  - tenacity=8.1.0=pyhd8ed1ab_0
  - termcolor=2.2.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=he1e0b03_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py311he2be06e_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - types-pytz=2022.7.1.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wandb=0.13.9=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.8.2=py311he2be06e_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.12.1=pyhd8ed1ab_0
  - zstd=1.5.2=hf913c23_6
prefix: /Users/gatiaher/mambaforge/envs/humansimEnv
